Frontend/telenor/map_telenor/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    #path('map/', views.map, name = 'map'),

app_name = 'map_telenor'

urlpatterns = [
    path('', views.cow_overview, name='cow_overview'),
    path('cow_update_note/<int:cow_id>/', views.cow_update_note, name='cow_update_note'),
]

Frontend/telenor/telenor/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('map_telenor.urls')),
    path('admin/', admin.site.urls),
]

Frontend/telenor/map_telenor/models.py
from django.db import models

class Cow(models.Model):
    cow_id = models.IntegerField(default=0)
    cow_name = models.CharField(max_length=200)
    notes = models.CharField(max_length=200)
    purchase_date = models.DateField('date purchased')
    service_date = models.DateField('date service')
    status_active = models.IntegerField(default=1)

    def __str__(self):
        return self.cow_name


class Sensor(models.Model):
    cow = models.ForeignKey(Cow, on_delete=models.CASCADE)
    sensor_type = models.CharField(max_length=200)
    sensor_value = models.IntegerField(default=0)
    time_stamp = models.DateTimeField('Last seen')

    def __str__(self):
        return self.sensor_type

Frontend/telenor/map_telenor/views.py
from django.shortcuts import render

from django.http import HttpResponse

from .telenor_queries import *

#This is temporary. The only view.

def cow_overview(request):
	data = get_cow_overview()
	return HttpResponse(data)

def cow_info(request, cow_id):
	data = get_cow_info(cow_id)
	return HttpResponse(data)



def index(request):
	return cow_overview(request)

def cow_overview(request): return render(request,'map_telenor/map.html', {'herd' :[get_cow_info(cow['cow_id']) for cow in get_cow_overview()]})



	#changing the project note and leave the rest unchanged

def cow_update_note(request, cow_id):
	new_note  = request.GET['note']
	update_cow_note(cow_id, new_note)
	return cow_overview(request)

Frontend/telenor/map_telenor/templates/map_telenor/base.html
<html lang="en">
{% load static %}
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="volrath" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Dashboard Template for Bootstrap</title>
    <!-- Copy-paste the stylesheet <link> into your <head> before all other stylesheets to load our CSS. -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">

    <!-- Latest compiled and minified CSS from MaxCDN-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript from MaxCDN -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <!-- Custom styles for this template -->

    <link rel="stylesheet" type="text/css" href={% static 'map_telenor/css/map_telenor.css' %}>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet"> <!-- Font h1 -->
    <link type="text/css" href="http://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet"> <!-- Font rest of the webpage see byggmesteran.css-->

<!-- style placed here to be available for html. -->
<style>
.navbar{
  margin-bottom: 0;
  border-radius: 0;
  border: 0;
  background-color: #586f93;
  height: 80px;
  width: 100%
}
.navbar-brand {
  min-height: 28px;
  padding: 0px 50px 50px;
}

.center {
  margin: 0 auto;
  width: 90%;

}

.sidebar {
  background-color: #ccc;
  border-radius: 0;
}

</style>

</head>

<!-- This is the base of the website. Extended in every html-file. -->
<body>

<<<<<<< HEAD
=======


>>>>>>> frontend_dev
<!--Header -->
  <nav class="navbar navbar-expand-lg" >
      <a class="navbar-brand" href="#"><img src="{% static 'map_telenor/images/tooltag_logo.png' %}" alt="tooltag_logo" width="100" height="40"></a>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
  <a class="nav-text" href="#" ><pre>[Admin] | Telenor </pre></a>
        </li>
  </nav>

<!-- Menu on side

  <div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 col-xs-1 p-l-0 p-r-0d-none d-md-block sidebar">
             <ul class="nav flex-column"> <br> <br>
              <li class="nav-item">
                <a class="nav-link" href="#">
                <p class="no_highlight"><span data-feather="map-pin"></span>Kart</p>

                </a>
              </li>
            </ul>

      </nav>

-->


  <main role="main" class="col-md ml-sm-auto col-lg pt-3 px-4">

  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">

<!-- Here every page is included -->
{% block body %}
{% endblock %}

    </div>

  </div>

</div>


</body>

<footer>

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>


  <!-- Icons -->
  <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
  <script>
    feather.replace()
  </script>

  <!-- Graphs -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>

</footer>

</html>

Frontend/telenor/map_telenor/templates/map_telenor/map.html
<!doctype html>

{% extends 'map_telenor/base.html' %}



{% block body %}
<header>

  <style>
         /* Set the size of the div element that contains the map */
        #overall_map {
          height: 700px ;  /* The height is 400 pixels */
          width: 100%;  /* The width is the width of the web page */
          position: center;
         }
  </style>
</header>

  <div class="container-fluid">


    <div class="row">
      <div class="col">

      </div>
    </div>

    <div class="row">
      <div class="col">


        <br></br>

           <!-- The google map -->

              <div class="jumpotron" id="overall_map"></div>

      </div>
    </div>
  </div>

{% for d in data %}
  {% if d.type == "gateway" %}
  <!-- Modal which show information about the gateway, included list of tools. Shown in the infoWindow -->
  <div class="modal fade" id="ModalMap{{d.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true"> <!-- Husk egen ID -->
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">

<p class="modal-title">UTSTYR</p>

{% for cow in herd %}
  <!-- Modal shown in the infoWindow -->
  <div class="modal fade" id="ModalMap{{cow.cow_id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true"> <!-- Husk egen ID -->
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title">Info om {{cow.cow_name}}</h2>

          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <table class="table table-sm table-hover">
            <thead>
              <tr>
                {% csrf_token %}
                {% for header in item_table_header%}
                 <th>{{header}}</th> <!-- Prints the header in table -->
                {% endfor %}
              </tr>
            </thead>
            <tbody>
              {% csrf_token %}

                  {% for tool in d.tools %}
                  <tr>

                      {% for tool_info in tool %}
                        {% if forloop.counter == 1 %}
                        <!-- don't display the tool_id -->
                        {% else %}
                          <td><p>{{tool_info}}</p></td>

                        {% endif %}
                      {% endfor %}

                  </tr>

              {% endfor %}
            </tbody>
          </table>


        </div>

          <div class="row">
            <div class="col">
              <ul>
                <li>  <h3> <strong>Generell info </strong></h3></li>
                <li><p><strong>Status: </strong> {% if cow.in_transit == 1 %} I bevegelse. {% else %} Stillestående. {% endif %} </p></li>
                <li><p><strong></p></li>
                <li><p><strong>Kjøpsdato: </strong>{{cow.purchased_date}}</p></li>
                <li><p><strong>Servicedato: </strong>{{cow.service_date}}</p></li>

                <li><h3><strong>Sensordata </strong></h3></li>
                <li> <p><strong>Temperatur i vogn: </strong>{{cow.temp}}°C </p></li>
                <li> <p><strong>Antenneretninga: </strong> {{cow.antenna_direction}}° </p></li> <!--  i forholdet til ka? -->
                <li> <p><strong>Strøm i vognen: </strong>{% if cow.power_on == 1 %} Ja {% else %} Nei {% endif %}</p></li>
                <li> <p><strong>Dør åpen:</strong> {% if cow.door_open == 1 %} Ja {% else %} Nei {% endif %} </p></li>
              </ul>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col">
              <h3><strong>Merknad</strong></h3>
              <form action = "{% url 'map_telenor:cow_update_note' cow.cow_id %}" method = "GET">
                {% csrf_token %}
                <input class="form-control" type="text" value="{{cow.note}}" id="note" name = "note">
              <input class="btn" type = "submit" id="submit" value="Lagre"></input>
              </form>

            </div>

          </div>

        </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Lukk</button>
      </div>
    </div>
  </div>
</div>


  {% else %}
  <!-- do nothing  -->


  {% endif %}

{% endfor %}

<footer>


<script src="jquery-3.3.1.min.js"></script>
<script>

<script type="text/javascript" charset="utf-8">

      // Initialize and add the map
      var marker;


      function save()
      {
        var value = marker.getPosition();

      }

      function initMap()
      {
        // The location of Uluru
        var uluru = {lat:  63.3, lng: 11.1 }; /* Start coordinates */

        // The map, centered at Uluru

        map = new google.maps.Map(document.getElementById('overall_map'), {zoom: 8, center:uluru});

        // Create new markers


          var marker{{forloop.counter}} = new google.maps.Marker({
  				      position: {lat : 63.73, lng : 10.4 },
  		          icon:
                  'http://maps.google.com/mapfiles/kml/paddle/blu-blank.png',

  		   		    map:map,
  		    });

/*Create a contentString to every marker.
For byggeplass: Link to redirect to construction_yard_details.
For gateway: Show a small list over tools registrated by this gateway in a modal. */

/* Gateway infoWindow */
          var contentStringGateway = '<div id="contentGateway">'+
                      '<div id="siteNotice">'+
                      '</div>'+
                      '<h3 id="firstHeading" class="firstHeading">{{d.name}}</h3>'+
                      '<div id="bodyContent">'+
                      '<p> <a role="button" class="btn btn-light btn-xs" data-toggle="modal" data-target="#ModalMap{{d.id}}"><span data-feather="plus"></span>'+
                      'Vis utstyr</a> '+
                      '</p>'+
                      '</div>'+
                      '</div>';
/* Project infoWindow */

          var contentStringProject = '<div id="contentProject">'+
                      '<div id="siteNotice">'+
                      '</div>'+
                      '<h3 id="firstHeading" class="firstHeading">{{d.name}}</h3>'+
                      '<div id="bodyContent">'+
                      '<p> <a class="no_highlight" href="#">'+
                      'Gå til byggeplass</a> '+
                      '</p>'+
                      '</div>'+
                      '</div>';


          var infoWindowIsClosed{{forloop.counter}} = true;

          if ("{{d.type}}" == "gateway") {
              var infoWindow{{forloop.counter}} = new google.maps.InfoWindow( {content : contentStringGateway });
          } else {
            var infoWindow{{forloop.counter}} = new google.maps.InfoWindow( {content : contentStringProject });
          }

        map = new google.maps.Map(document.getElementById('overall_map'), {zoom: 5, center:uluru});

        // Create new markers

        {% for cow in herd %}
          var marker{{forloop.counter}} = new google.maps.Marker({
  				      position: {lat : {{cow.lat}}, lng : {{cow.long}} },
  		          icon:

                {% if cow.in_transit == 1 %}
                  'http://maps.google.com/mapfiles/kml/paddle/blu-blank.png',
                {% elif cow.in_service == 1%}
                  'http://maps.google.com/mapfiles/kml/paddle/grn-blank.png',
                {% else %}
                  'http://maps.google.com/mapfiles/kml/paddle/red-blank.png',

                {% endif %}
  		   		    map:map,
  		    });




          var content = '<div id="content">'+

                      '<div id="siteNotice">'+
                      '</div>'+
                      '<h3 id="firstHeading" class="firstHeading">{{cow.cow_name}}</h3> '+
                      '<hr>'+
                      '<div class="row" id="bodyContent">'+
                      '<div class="col">'+
                      '<ul>'+
                      '<li><p>'+
                      'Status: {% if cow.in_transit == 0 %} Ikke i bevegelse. {% else %} i bevegelse. Sjekk merknadsfelt for hvor den er ventet.{% endif %} '+
                      '</p></li>'+
                      '<li><p>'+
                      '<strong>Neste service: </strong>{{cow.service_date}}'+
                      '</p></li>'+
                      '</ul>'+
                      '</div>'+
                      '</div>'+
                      '<div class="row" id="bodyContent">'+
                      '<div class="col">' +
                      '<a role="button" class="btn btn-light btn-xs" data-toggle="modal" data-target="#ModalMap{{cow.cow_id}}"><span data-feather="plus"></span>'+
                      'Vis mer info</a> '+
                      '</div>'+
                      '</div>';

          var infoWindowIsClosed{{forloop.counter}} = true;
          var infoWindow{{forloop.counter}} = new google.maps.InfoWindow( {content : content});





          marker{{forloop.counter}}.addListener('click', function() {
            if(infoWindowIsClosed{{forloop.counter}} == true)
            {
              infoWindow{{forloop.counter}}.open(map, marker{{forloop.counter}});
              infoWindowIsClosed{{forloop.counter}} = false;
            }

            else {
              infoWindow{{forloop.counter}}.close(map, marker{{forloop.counter}});
                infoWindowIsClosed{{forloop.counter}} = true;

            }


          });

            else
            {
              infoWindow{{forloop.counter}}.close(map, marker{{forloop.counter}});
                infoWindowIsClosed{{forloop.counter}} = true;
            }
          });
          {% endfor %}

    }

    </script>

    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhtkGgx24FdCmrajIYdbPaC_w-j5vGwgY&callback=initMap">
    </script>

    <script type='text/javascript' src='//cdnjs.cloudflare.com/ajax/libs/knockout/3.4.2/knockout-min.js'></script>

</footer>
{% endblock %}