Frontend/mysite/byggmesteran/urls.py
__author__ = 'volrath'

from django.urls import path
from . import views

app_name = 'byggmesteran'

urlpatterns = [
    path('', views.index, name = 'index'),
	path('construction_yard/<int:finished>/', views.construction_yard, name='construction_yard'),
    path('construction_yard_details/<int:project_id>/', views.construction_yard_details, name='construction_yard_details'),
    path('construction_yard/edit/<int:creating_new_project>/<int:project_id>/', views.construction_yard_details_edit, name='construction_yard_details_edit'),

    path('counstruction_edit_update_project/<int:creating_new_project>/<int:project_id>/', views.counstruction_edit_update_project, name ="counstruction_edit_update_project"),
    path('project_update_note/<int:project_id>/', views.project_update_note, name = "project_update_note"),
    path('set_project_status/<int:project_id>/<int:value>/', views.set_project_status, name = "set_project_status"),
    path('construction_delete/<int:project_id>/<int:is_finished>/', views.construction_delete, name = "construction_delete"),

    path('warehouse/', views.warehouse, name = 'warehouse'),

    path('overall_map/<int:gateway_selected>/<int:project_selected>/', views.overall_map, name = 'overall_map'),


    path('contacts/', views.contacts, name = 'contacts'),
    path('contact_edit/<int:new_contact>/<int:contact_id>', views.contact_edit, name = "contact_edit"),
    path('contact_update/<int:new_contact_added>/<int:contact_id>/', views.contact_update, name = "contact_update"),

    path('tool_edit_update/<int:tool_id>/', views.tool_edit_update, name = 'tool_edit_update'),
    path('tool_edit/<int:tool_id>/', views.tool_edit, name = "tool_edit"),
    path('tool/<int:category_id>',views.tool, name = 'tool'),
    ]

Frontend/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('byggmesteran.urls')),
    path('admin/', admin.site.urls),
]

Frontend/mysite/byggmesteran/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Adresses(models.Model):
    adress_id = models.AutoField(primary_key=True)
    street = models.CharField(max_length=45, blank=True, null=True)
    postal_code = models.IntegerField(blank=True, null=True)
    long = models.DecimalField(max_digits=10, decimal_places=7, blank=True, null=True)
    lat = models.DecimalField(max_digits=10, decimal_places=7, blank=True, null=True)
    place_name = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'adresses'


class Categories(models.Model):
    category_id = models.AutoField(primary_key=True)
    category_name = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'categories'


class Contacts(models.Model):
    contact_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=45, blank=True, null=True)
    phone = models.IntegerField()
    email = models.CharField(max_length=45)

    class Meta:
        managed = False
        db_table = 'contacts'


class Gateways(models.Model):
    gateway_id = models.AutoField(primary_key=True)
    gateway_uid = models.IntegerField(blank=True, null=True)
    gateway_name = models.CharField(max_length=45, blank=True, null=True)
    long = models.DecimalField(max_digits=10, decimal_places=7, blank=True, null=True)
    lat = models.DecimalField(max_digits=10, decimal_places=7, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'gateways'


class Measurements(models.Model):
    tool = models.ForeignKey('Tools', models.DO_NOTHING)
    gateway = models.ForeignKey(Gateways, models.DO_NOTHING)
    project = models.ForeignKey('Projects', models.DO_NOTHING)
    last_seen = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'measurements'


class Projects(models.Model):
    project_id = models.AutoField(primary_key=True)
    contact = models.ForeignKey(Contacts, models.DO_NOTHING)
    name = models.CharField(max_length=45, blank=True, null=True)
    start_date = models.DateTimeField(blank=True, null=True)
    finish_date = models.DateTimeField(blank=True, null=True)
    note = models.CharField(max_length=400, blank=True, null=True)
    adress = models.ForeignKey(Adresses, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'projects'


class Tools(models.Model):
    tool_id = models.AutoField(primary_key=True)
    type = models.ForeignKey('Types', models.DO_NOTHING, blank=True, null=True)
    tool_name = models.CharField(max_length=45, blank=True, null=True)
    manufacturer = models.CharField(max_length=45, blank=True, null=True)
    note = models.CharField(max_length=200, blank=True, null=True)
    service_date = models.DateTimeField(blank=True, null=True)
    purchased_date = models.DateTimeField(blank=True, null=True)
    rssi = models.IntegerField(blank=True, null=True)
    uid = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'tools'


class Types(models.Model):
    type_id = models.AutoField(primary_key=True)
    type_name = models.CharField(max_length=45, blank=True, null=True)
    category = models.ForeignKey(Categories, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'types'

Frontend/mysite/byggmesteran/forms.py
from django import forms


class TestForm(forms.Form):
	post = forms.CharField()

Frontend/mysite/byggmesteran/views.py
from .queries import *

from .models import *
from django.views.generic import TemplateView
from .forms import TestForm


from django.shortcuts import render
from django.http import HttpResponse
from datetime import datetime





def index(request):
	"""Redirects to the project-overview site -'construction_yard.html' when
	typing byggmesteran.tooltag.no/

    Args:
        request (HttpRequest):

    Returns:
        HttpResponse :  A HttpResponse object a django object which django use to render webpage
    """

	return construction_yard(request, 0)


def construction_yard(request, finished):
	"""Render the "main-page" which shows a overview of all the projects
	which statisfy project.is_finshed == finished

    Args:
		request (HttpRequest):
		finished (bool)  :

    Returns:
        HttpResponse :  A HttpResponse object a django object which django use to render webpage
    """

	#a list of list, where the elements in the innerlist is the project attributes.
	project_overview = get_project_overview(finished)

	#removes the warehouse
	project_overview.pop(0) #Yeah the warehouse/"lager" is hardcoded as the first element (this may lead to some problems in the futere)

	#A dictionary of value, where the keys are used in the HTML and are referring to the dict-values
	context = {
		'Company_name'    : 'Byggmesteran',
		'project_overview': project_overview,
		'finished'        : finished
		}
	return render(request, 'byggmesteran/construction_yard.html', context)

def warehouse(request):
	"""Render the "lager"-page, which shows details about the "lager"

    Args:
        request (HttpRequest):

    Returns:
        HttpResponse :  A HttpResponse object a django object which django use to render webpage
    """
	item_table = get_project_tools(1)# a list of tools registered in project 1 (lager'et)
	project_info = get_project_info(1)# general information  for the "lager"
	#NOT IF THE WAREHOUSE ID CHANGE FROM 1, WE ARE IN TROUBLE... :)

	#A dictionary of value, where the keys are used in the HTML and are referring to the dict-values
	context = {
		'Company_name'            : 'Byggmesteran',
		'item_table_header'       : ('Navn', 'Kategori', 'Type', 'Sist registrert', 'Merknad'),
		'item_table'              : item_table,
		'warehouse_name'          : project_info[0],
		'warehouse_start_date'    : project_info[1].strftime('%d-%m-%Y'),
		'warehouse_end_date'      : project_info[2].strftime('%d-%m-%Y'),
		'warehouse_note'          : project_info[3],
		'warehouse_contact_name'  : project_info[4],
		'warehouse_contact_number': project_info[5],
		'warehouse_email'         : project_info[6],
		'warehouse_street'        : project_info[7],
		'warehouse_postal_code'   : project_info[8],
		'warehouse_id'            : 1
		}
	#hardcoded indices :)

	return render(request, 'byggmesteran/warehouse.html', context)


def construction_yard_details(request, project_id):
	"""Render a webpage whith detailes about the selected project

    Args:
		request (HttpRequest):
		project_id (int)     :  The project_id of the desired project

    Returns:
        HttpResponse :  A HttpResponse object a django object which django use to render webpage
    """

	item_table = list(get_project_tools(project_id))#list of tools in the project
	for i in range(len(item_table)):
		item_table[i] = list(item_table[i])
		item_table[i][4] = item_table[i][4].strftime('%d-%m-%Y. %H:%M')#formating the time

	project_info = get_project_info(project_id)# general information for the desired project

	#A dictionary of value, where the keys are used in the HTML and are referring to the dict-values
	context = {
		'Company_name'       : 'Byggmesteran',

		'item_table_header'     : ('Navn', 'Kategori', 'Type', 'Sist registrert', 'Merknad'),
		'item_table'            : item_table,
		'project_name'          : project_info.name,
		'project_note'          : project_info.note,
		'project_start_date'    : project_info.start_date.strftime('%d-%m-%Y'),
		'project_end_date'      : project_info.finish_date.strftime('%d-%m-%Y'),
		'project_street'        : project_info.address_street, #unused
		'project_postal_code'   : project_info.address_postal_code,#unused
		'project_is_finished'   : project_info.is_finished,
		'project_contact_name'  : project_info.contact_name,
		'project_contact_number': project_info.contact_phone,
		'project_email'         : project_info.contact_email,
		'long'                  : project_info.long,
		'lat'                   : project_info.lat,
		'project_radius'        : project_info.radius, #unused
		'project_address_id'    : project_info.address_id,
		'project_contact_id'    : project_info.contact_id,
		'project_id'            : project_id,
		'positions'             : [project_info.long, project_info.lat],

		}

	return render(request, 'byggmesteran/construction_yard_details.html', context)


def construction_yard_details_edit(request, creating_new_project, project_id):
	"""Render a webpage in which the user can create a new project or edit an already existing project

    Args:
		request (HttpRequest)      :
		creating_new_project (bool): Indicates whether the user is creating a new project or not(editing an existing)
		project_id (int)           : The id of the project which a user is going to edit, a 'DON'T CARE' if creating_new_project == True

    Returns:
        HttpResponse :  A HttpResponse object a django object which django use to render webpage
    """

	#a list of list, where the elements in the innerlist is the project attributes.

	contacts = get_contacts() # alist of all contacts

	if creating_new_project:#a user is creating a new project

		#A dictionary of value, where the keys are used in the HTML and are referring to the dict-values
		context = {
			'caption'          		: 'Nytt prosjekt',
			'contacts'              : contacts,
			'long'                  : 11.4709864,
			'lat'                   : 63.7922438,
			'project_start_date'    : datetime.now().strftime('%Y-%m-%d'),
			'project_end_date'      : datetime.now().strftime('%Y-%m-%d'),
			'new_project'			: True,

			#by default we set the contact as the first contact in the list of all contacts
			'project_contact_name'  : contacts[0].name,
			'project_contact_number': contacts[0].phone,
			'project_email'         : contacts[0].email,
			'project_contact_id'    : contacts[0].contact_id,

		}

		return render(request, 'byggmesteran/construction_yard_details_edit.html', context)

	project_info = get_project_info(project_id)#project info

	#A dictionary of value, where the keys are used in the HTML and are referring to the dict-values
	context = {
		'Company_name'          : 'Byggmesteran',
		'caption'          		: 'Rediger prosjekt',
		'contacts'              : contacts,
		'project_name'          : project_info.name,
		'project_start_date'    : project_info.start_date.strftime('%Y-%m-%d'),
		'project_end_date'      : project_info.finish_date.strftime('%Y-%m-%d'),
		'project_note'          : project_info.note,
		'project_contact_name'  : project_info.contact_name,
		'project_contact_number': project_info.contact_phone,
		'project_email'         : project_info.contact_email,
		'long'                  : project_info.long,
		'lat'                   : project_info.lat,
		'project_radius'        : project_info.radius,
		'project_contact_id'    : project_info.contact_id,
		'project_id'            : project_id,
		}

	return render(request, 'byggmesteran/construction_yard_details_edit.html', context)




def tool(request, category_id):
	"""Render a webpage which contains all information for all the tools in the system

	NB! category_id is a don't care

    Args:
		request (HttpRequest) :
		category_id (int) : DONT CARE // old functionallity

    Returns:
        HttpResponse :  A HttpResponse object a django object which django use to render webpage
    """

	#a list of list, where the elements in the innerlist is the project attributes.
	categories = get_categories()
	#tools.tool_id, tools.tool_name, types.type_name, tools.manufacturer, tools.purchased_date, tools.service_date, a.last_seen, projects.name, tools.note
	types_by_category = [get_types_by_category(c[0]) for c in categories ]

	#creating all list of all tools that exist, and formating it
	tool_all = []
	for c in get_categories():
		tool_cat = get_tools_by_category(c[0])
		tool_cat_edit = []
		for tool in tool_cat:
			it = list(tool)
			it[4] = it[4].strftime('%d-%m-%Y') if it[4] is not None else it[4]
			it[5] = it[5].strftime('%d-%m-%Y') if it[5] is not None else it[5]
			it[6] = it[6].strftime('%d-%m-%Y. %H:%M') if it[6] is not None else it[6]
			tool_cat_edit.append(it)
		tool_all.append(tool_cat_edit)


	#A dictionary of value, where the keys are used in the HTML and are referring to the dict-values
	context = {
		'item_table_header': ('Navn', 'Type', 'Merke', 'Innkj.dato', 'Servicedato', 'Sist tid registrert', 'Sist sted registrert', 'Merknad'),
		'Company_name'     : 'Byggmesteran',
		'categories'       : categories,
		'types_by_category': types_by_category,
		'tool_all'         : tool_all,
		}

	return render(request, 'byggmesteran/tool.html', context)



def contacts(request):
	"""Render a webpage which contains all the contacts that exist

    Args:
		request (HttpRequest) :

    Returns:
        HttpResponse :  A HttpResponse object a django object which django use to render webpage
    """
	context = {
		'item_table_header': ('Navn','telefon', 'email'),
		'Company_name'     : 'Byggmesteran',
		'contacts'         : [ c for c in get_contacts() ],
	}
	return render(request, 'byggmesteran/contacts.html', context)

def contact_edit(request, new_contact, contact_id):
	"""Render a webpage in which the user can create a new contact or edit an already existing contact

    Args:
		request (HttpRequest) :
		new_contact (bool): Indicates whether the user is creating a new contact or not(editing an existing)
		project_id (int) : The id of the contact which a user is going to edit, a 'DON'T CARE' if creating_new_project == True

Frontend/mysite/byggmesteran/templates/byggmesteran/base.html
<!-- This code is extended to all html files. In the head of this file all stylesheets are included. -->

<html lang="en">
{% load static %}
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="volrath" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <!-- Copy-paste the stylesheet <link> into your <head> before all other stylesheets to load our CSS. -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">

    <!-- Latest compiled and minified CSS from MaxCDN-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript from MaxCDN -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <!-- Adding CSS -->

    <link rel="stylesheet" type="text/css" href={% static 'byggmesteran/css/byggmesteran.css' %}>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet"> <!-- Font h1 -->
    <link type="text/css" href="http://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet"> <!-- Font rest of the webpage see byggmesteran.css-->

<!-- style placed here to be available for html. -->
<style>
.navbar{
  margin-bottom: 0;
  border-radius: 0;
  border: 0;
  background-color: #586f93;
  height: 80px;
  width: 100%
}
.navbar-brand {
  min-height: 28px;
  padding: 0px 50px 50px;
}

.center {
  margin: 0 auto;
  width: 90%;

}

.sidebar {
  background-color: #ccc;
  border-radius: 0;
}

</style>

</head>

<!-- This is the base of the website. The body contains everything that is similar in every template. i.e  header of page and sidebar. -->
<body>

<!--Header -->
  <nav class="navbar navbar-expand-lg" >
      <a class="navbar-brand" href="#"><img src="{% static 'byggmesteran/images/tooltag_logo.png' %}" alt="tooltag_logo" width="100" height="40"></a>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
  <a class="nav-text" href="#" ><pre>[Admin] | Byggmesteran </pre></a>
        </li>
  </nav>


<!-- Menu on side. Keep everything inside containers, and divide it into rows and col. Google Bootstrap for more info. -->

  <div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 col-xs-1 p-l-0 p-r-0d-none d-md-block sidebar">
             <ul class="nav flex-column"> <br> <br>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'byggmesteran:construction_yard' 0 %}">
                <p class="no_highlight"><span data-feather="map-pin"></span>Byggeplasser</p>

                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'byggmesteran:warehouse' %}">
                <p class="no_highlight"><span data-feather="home"></span> På lager </p>
                </a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'byggmesteran:tool' 1 %}">
                  <p class="no_highlight"><span data-feather="box"></span> Utstyr</p>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'byggmesteran:contacts' %}">
                  <p class="no_highlight"><span data-feather="users"></span> Kontakter</p>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'byggmesteran:overall_map' 1 1 %}"> <!-- url 'byggmesteran:overall_map' 1 1 -->
                  <p class="no_highlight"><span data-feather="rss"></span> Kart</p>
                </a>
              </li>
          <!--    <li class="nav-item">
                <a class="nav-link" href="#">
                  <p class="no_highlight"><span data-feather="layers"></span> Historikk</p>
                </a>
              </li> -->
            </ul>

      </nav>




  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">

  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3">

<!-- Here every page is included -->
{% block body %}
{% endblock %}

    </div>

  </div>

</div>


</body>

<footer>

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>


  <!-- Icons -->
  <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
  <script>
    feather.replace()
  </script>

  <!-- Graphs -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>

</footer>

</html>

Frontend/mysite/byggmesteran/templates/byggmesteran/construction_yard.html
<!doctype html>

{% extends 'byggmesteran/base.html' %}

{% block body %}
<main>
  <div class="container">
    <h2><strong>ALLE{% if finished == 0 %} AKTIVE {% else %} INAKTIVE {% endif %} BYGGEPROSJEKTER </strong></h2>
    <hr>

    <div class="row" style="margin-bottom:20px">
      <div class="col">

        <a class="btn btn-light" href="{% url 'byggmesteran:construction_yard_details_edit' 1 1 %}" role="button"><span data-feather="plus"></span> Nytt prosjekt </a>
        {% if finished == 1 %} <!-- Which button depends on active status -->
        <a class="btn btn-light" href="{% url 'byggmesteran:construction_yard' 0 %}" role="button"><span data-feather="chevron-right"></span> Gå til aktive</a>
        {% else %}
        <a class="btn btn-light" href="{% url 'byggmesteran:construction_yard' 1 %}" role="button"><span data-feather="chevron-right"></span> Gå til inaktive</a>
        {% endif %}

      </div>
    </div>


<br></br>
<!-- Presenting the projects. If finished == 0 inactive projects show. 1 -> show active.-->
  <div class="row">
    <div class="center">

      {% for construction in project_overview %} <!-- Loops through list over all the projects -->
        <div class="col-md-3 col-centered">
            <a href= "{% url 'byggmesteran:construction_yard_details' construction.0 %}">
              {% if finished == 0%}
              <button type="button" class="btn btn-success btn-circle btn-xl">
              {% else %}
                <button type="button" class="btn btn-danger btn-circle btn-xl">
              {% endif %}
                <div class="caption">
                  <span data-feather="map-pin" style="color:black"></span>
                </div>
              </button>
            </a>
          <!-- Text underneath  -->
          <h3>{{construction.1}}</h3>

        </div>
      {% endfor %}
    </div>
  </div>
  </div>

</main>




{% endblock %}

Frontend/mysite/byggmesteran/templates/byggmesteran/construction_yard_details.html
<!doctype html>

{% extends 'byggmesteran/base.html' %}


{% block body %}

<style>
   /* Set the size of the div element that contains the map */
  #map {
    height: 400px;  /* The height is 400 pixels */
    width: 100%;  /* The width is the width of the web page */
   }
</style>

<div class="container-fluid">
<!-- The title is dependent on whether or not the prosject is finished. -->
  <h2>Byggeplass: <strong>{{ project_name }}</strong> {% if project_is_finished == 1 %} <span class="dot_red"></span> {% else %} <span class="dot_green"></span> {% endif %}</h2>
  <hr>
<!-- Makes buttons for navigation -->
  <div class="row" style="margin-bottom: 20px">
    <div class="col">
      <a class="btn btn-light" href="{% url 'byggmesteran:construction_yard_details_edit' 0 project_id %}" role="button"><span class="glyphicon glyphicon-cog"></span> Rediger prosjekt </a>

       <a class="btn btn-light" data-toggle="modal" data-target="#modal" role="button"><span class="glyphicon glyphicon-trash"></span> Fjern prosjekt</a>

      <a class="btn btn-light" href= {% if project_is_finished == 1 %} "{% url 'byggmesteran:set_project_status' project_id 0 %}" {% else %} "{% url 'byggmesteran:set_project_status' project_id 1 %}" {% endif %} role="button"><span data-feather="archive"></span> Gjør {% if project_is_finished == 0 %} <span> inaktiv </span> {% else %} <span> aktiv </span> {% endif %} </a>
    </div>
  </div>

  <div class="row" style="margin-bottom: 20px">
    <div class = "col-md-4"> <!-- Col contains in of the project -->
      <h3> Info </h3>
    <!--  <p>
        <span class="glyphicon glyphicon-map-marker"></span>
        Adresse: {{ project_street }}, {{ project_postal_code }}
      </p> -->
      <p>
        <span class="glyphicon  glyphicon-calendar"></span>
        Startdato: {{ project_start_date }}
      </p>
      <p>
        <span class="glyphicon  glyphicon-calendar"></span>
        Sluttdato: {{project_end_date}}
      </p>
      <p>
        <a href="#" class="no_highlight">
        <span class="glyphicon glyphicon-user"></span>
        </a>
        Prosjektleder: {{project_contact_name}}
        </p>
        <p>
          <span class="glyphicon glyphicon-earphone"></span>
          Telefonnummer: {{project_contact_number}}
        </p>
        <p>
          <a href="mailto:{{project_email}}" target="_top" class="no_highlight">
          <span class="glyphicon glyphicon-envelope"></span>
          E-mail: {{project_email}}
          </a>
        </p>

      </div>


      <div class="col-md-4">
        <!-- Added to make space -->

      </div>

      <div class="col-md-4"> <!-- Editable textbox -->
        <form action = "{% url 'byggmesteran:project_update_note' project_id %}">
        <label for="exampleFormControlTextarea1"><h3> Merknad for lager</h3></label>
        <p><textarea class="form-control" id="project_note" rows="3" value = "{{project_note}}" name = "project_note">{{project_note}}</textarea></p>
        <input type="submit" id="submit" value="Lagre">
        </form>
      </div>
    </div> <!-- End row -->

    <div class="row">
      <div class="col">
        <h3>Utstyr på byggeplass</h3>
        {% include 'byggmesteran/base_table.html' %}
      </div>
    </div>

<div class="row">
  <div class="col">
    <h3> Kart over byggeplassen </h3>
      <div id="map"></div>
  </div>
</div>

</div>

<!-- Modal window show when you want to remove a prosject. Makes sure the user really wants to delete it. -->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">INFO</h5>
        <!-- ID is used to be able to refer to this modal, and to be able to change the CSS on this exact modal. This also yields for other classes. -->
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Vil du virkelig slette DETTE prosjektet? Dette medfører at all datahistorikk assosiert med prosjektet slettes. For å beholde denne historikken kan man sette prosjektet som inaktivt.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Tilbake</button>
        <form action = "{% url 'byggmesteran:construction_delete' project_id project_is_finished %}" >
        <input type="submit" class="btn btn-danger" value = "SLETT" />
        </form>
      </div>
    </div>
  </div>
</div>

<script>
  // Initialize and add the map

  function initMap()
  {
    // The default location
    var uluru = {lat: {{lat}}, lng: {{long}} };

    // The map, centered at var uluru
    var map = new google.maps.Map(document.getElementById('map'), {zoom: 8, center:uluru});
    var marker = new google.maps.Marker({position: uluru, map:map});


}


</script>
<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhtkGgx24FdCmrajIYdbPaC_w-j5vGwgY&callback=initMap">
</script>

<script type='text/javascript' src='//cdnjs.cloudflare.com/ajax/libs/knockout/3.4.2/knockout-min.js'></script>



{% endblock %}

Frontend/mysite/byggmesteran/templates/byggmesteran/index.html
<!-- Not in use -->

<!doctype html>

{% extends 'byggmesteran/base.html' %}


{% block body %}


    <tr>
      <div class="container">
          <div class="well"><h2> <strong>STARTSIDE</strong></h2></div>
        </div>
    </tr>
  </div>

<!--
  <canvas class="my-4" id="myChart" width="900" height="380"></canvas>
-->



{% endblock %}